### ISSUE TITLE
fps display has problems staying on the position

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/ShowFPS#2]
As mentioned here:
https://forum.kerbalspaceprogram.com/index.php?/topic/172692-112x-showfps/&do=findComment&comment=4176724

I see that the fps display has problems staying on the position when I position it next to the top right VAB buttons, see screenshot:
![1](https://i.imgur.com/Ru99omJ.jpg)

As soon as I click on the "Save" button the fps display moves to here:
![2](https://i.imgur.com/tFm4jq7.jpg)

When I leave the VAB by clicking the rightmost button the fps view is moved even more to the right, as can be seen in SPC:
![3](https://i.imgur.com/uzqTeGu.jpg)

**Comment by linuxgurugamer** [comment]
Fixed and released

**Comment by Gordon-Dry** [comment]
Last session was good. It was the first session with the updated version 0.3.3.1.

Now I launched KSP and as I reached the SPC I recognized that the fps overlay was slightly more to the right and down than before.
As I clicked on it (while holding the mouse button to drag it) it moved leftwards in "huge jumps", I could see it for a blink of an eye near the top center, I've shortly seen it at the top left and then is disappeared.

I have to admit that I already pressed F8 while in the main menu, and as I use the mod [S.A.V.E.](https://github.com/linuxgurugamer/S.A.V.E/) which got a UI on the top right in the main menu, I could not see the fps overlay ands assume it was behind that UI.
So I also could not see if it already was moved slightly to the right and down as mentioned above.

The only logged to the Player.log was
```
[ShowFPS: OnMouseDown 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[ShowFPS: OnMouseUp 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

The settings.cfg as it was before game start and still is:
```
position_x = 1797
position_y = 14
plugin_key = F8
fontSize = 10
showPerfectSym = False
periodicRescale = False
frequency = 1
alpha = 1
winX = 474
winY = 177
```

After the above occurance I did a scene change to the Tracking Station and back and then quit to the Main Menu, but those did nothing, the settings.cfg did not change.
I really would like to see what's the coordinates now without quitting the game.

Logs:
[2022111601.zip](https://github.com/linuxgurugamer/ShowFPS/files/10025128/2022111601.zip)

**Comment by linuxgurugamer** [comment]
yuck.  It was working for me last night, I'm just going to redo all the code for the positioning, so it may take a few days.
There was a reason I had disabled this functionality, brought it back upon request

**Comment by Gordon-Dry** [comment]
After quitting the game properly via main menu the settings.cfg was overwritten, but the coordinates did not change.
So those coordinates still represent the top right position.
I will boot up KSP soon and see what happens if I only press F8 and then try to reproduce or not by clicking the overlay again.

**Comment by linuxgurugamer** [comment]
I finally figured it out, the size of the text field was hard-coded to 200 pixels.
I've reduced it to the size of the text only.
Please try this beta and let me know how it goes:

https://www.dropbox.com/s/28yslymo559w0pf/ShowFPS-0.3.1.1.zip?dl=0

**Comment by Gordon-Dry** [comment]
Okay, I will do.

I just wanted to report my latest finding before I update:
This time I waited until I reached the SPC before I pressed F8, the overlay was where it was the last time (slightly off as well) and after clicking on it shortly (no dragging with clicked mouse button) it popped to the top left.
As it was there I was able to drag it.
Clicking on it - even after pressing F8 or a scene change - was no issue now.
Then I left to the main menu and was able to see it shining through the S.A.V.E. UI - so yesterday it was not there as I did not see it shining through, it appeared after loading the save and reaching the SPC and then the abovementioned issue occured.

**Comment by linuxgurugamer** [comment]
Just to be clear, this report is using the released 0.3.1.1, not the beta?

**Comment by Gordon-Dry** [comment]
Yes.

**Comment by Gordon-Dry** [comment]
Works now with beta.
And it spams the log with
```
[ShowFPS]: x, y: 1650, 1 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```
;)

**Comment by linuxgurugamer** [comment]
I did say it was a beta.

I'll remove the logging and release, thanks for testing
